Traceback (most recent call last):
  File "/home/ttc-user/GetContent/main.py", line 6, in <module>
    from aiogram import Bot, Dispatcher, html
ModuleNotFoundError: No module named 'aiogram'
Traceback (most recent call last):
  File "/home/ttc-user/GetContent/main.py", line 6, in <module>
    from aiogram import Bot, Dispatcher, html
  File "/home/ttc-user/.local/lib/python3.10/site-packages/aiogram/__init__.py", line 6, in <module>
    from . import enums, methods, types
  File "/home/ttc-user/.local/lib/python3.10/site-packages/aiogram/methods/__init__.py", line 1, in <module>
    from .add_sticker_to_set import AddStickerToSet
  File "/home/ttc-user/.local/lib/python3.10/site-packages/aiogram/methods/add_sticker_to_set.py", line 5, in <module>
    from ..types import InputSticker
  File "/home/ttc-user/.local/lib/python3.10/site-packages/aiogram/types/__init__.py", line 397, in <module>
    _entity.model_rebuild(
  File "/home/ttc-user/.local/lib/python3.10/site-packages/pydantic/main.py", line 470, in model_rebuild
    return _model_construction.complete_model_class(
  File "/home/ttc-user/.local/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 501, in complete_model_class
    schema = gen_schema.clean_schema(schema)
  File "/home/ttc-user/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 405, in clean_schema
    schema = _discriminated_union.apply_discriminators(schema)
  File "/home/ttc-user/.local/lib/python3.10/site-packages/pydantic/_internal/_discriminated_union.py", line 60, in apply_discriminators
    return simplify_schema_references(_core_utils.walk_core_schema(schema, inner))
  File "/home/ttc-user/.local/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 460, in simplify_schema_references
    schema = walk_core_schema(schema, collect_refs)
  File "/home/ttc-user/.local/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 431, in walk_core_schema
    return f(schema.copy(), _dispatch)
  File "/home/ttc-user/.local/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 447, in collect_refs
    recurse(definition, collect_refs)
  File "/home/ttc-user/.local/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 207, in walk
    return f(schema, self._walk)
  File "/home/ttc-user/.local/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 450, in collect_refs
    ref = get_ref(s)
  File "/home/ttc-user/.local/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 129, in get_ref
    return s.get('ref', None)
KeyboardInterrupt
